events { worker_connections 1024; }

http {
    # Логирование запросов в формате, удобном для мониторинга
    log_format main '{"remote_addr": "$remote_addr", "time": "$time_local", "request": "$request", "status": "$status"}';
    access_log /var/log/nginx/access.log main;

    upstream ml_app {
        server ml_service:5000;
    }

    server {
        listen 80;

        # Перенаправление всех входящих запросов на Flask контейнер
        location / {
            proxy_pass http://ml_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}